# Create a table to store results
CREATE TABLE files (lines STRING);

# Load data into the database using a file on your local system (NOT HDFS)
LOAD DATA LOCAL INPATH '/file01.txt' INTO TABLE files;

# Create a new table using data from the files table
CREATE TABLE word_counts AS
SELECT word, count(1) AS count FROM
(SELECT explode(split(lines, ' ')) AS word FROM files) W
GROUP BY word
ORDER BY word;